databases:
  - name: recipe
    databaseName: recipe
    user: recipe_vnhn_user

services:
  - type: web
    name: Atoke
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false